import { describe, expect, test } from 'bun:test';
import type { VcsChangedFile } from '../../src/vcs/types';
import {
    analysisFor,
    classifyFile,
    classifyPath,
    defaultClassificationRules,
    type FileClass,
    fileClasses,
    GENERATED_MARKER_BYTES,
    isNoiseClass
} from '../../src/analysis/classification';
import { assessRisk } from '../../src/analysis/risk';
import { riskRulesForClassification } from '../../src/analysis/risk-rules';

const RULES = defaultClassificationRules();

function changedFile(path: string, additions = 1, previousPath?: string): VcsChangedFile {
    return { path, status: 'modified', additions, deletions: 0, previousPath, patch: { state: 'none' } };
}

describe('classification taxonomy', () => {
    test('classifies representative paths with the canonical taxonomy', () => {
        // eslint-disable-next-line anti-slop/no-known-value-widening -- taxonomy fixture maps representative paths to their canonical class
        const cases: Record<string, FileClass> = {
            'src/engine/runtime.ts': 'source',
            'scripts/build-release.ts': 'source',
            'action/resolve-engine.ps1': 'source',
            'tests/analysis/risk.test.ts': 'test',
            'tests/fixtures/risk-cases.json': 'test',
            'README.md': 'docs',
            'docs/architecture.md': 'docs',
            '.github/workflows/ci.yml': 'config',
            'package.json': 'config',
            'bun.lock': 'lockfile',
            'packages/app/package-lock.json': 'lockfile',
            'vendor/thirdparty/lib.c': 'vendor',
            'node_modules/pkg/index.js': 'vendor',
            'assets/logo.png': 'asset',
            'public/fonts/inter.woff2': 'asset',
            'src/maps/bundle.js.map': 'generated',
            'src/maps/bundle.min.js': 'generated',
            '.gitignore': 'other',
            '.ts': 'other',
            Jenkinsfile: 'other',
            Makefile: 'config',
            'notes/unknown.zzz': 'other'
        };

        for (const [path, expected] of Object.entries(cases)) {
            expect(classifyPath(path, RULES)).toBe(expected);
        }
    });

    test('every class is reachable and noise classes are explicit', () => {
        expect(new Set(fileClasses).size).toBe(fileClasses.length);
        expect(isNoiseClass('lockfile')).toBe(true);
        expect(isNoiseClass('generated')).toBe(true);
        expect(isNoiseClass('vendor')).toBe(true);
        expect(isNoiseClass('asset')).toBe(true);
        expect(isNoiseClass('source')).toBe(false);
        expect(isNoiseClass('test')).toBe(false);
        expect(isNoiseClass('docs')).toBe(false);
        expect(isNoiseClass('config')).toBe(false);
        expect(isNoiseClass('other')).toBe(false);
        expect(analysisFor('source')).toEqual({ scc: 'counted', cccc: 'attempted' });
        expect(analysisFor('lockfile')).toEqual({ scc: 'not-counted', cccc: 'unsupported' });
    });

    test('detects generated content markers only in the first bytes and honors exceptions', () => {
        const generated = classifyFile({
            path: 'src/api/client.ts',
            content: `// @generated by tool\n${'x'.repeat(GENERATED_MARKER_BYTES * 2)}`,
            rules: RULES
        });

        expect(generated.classification).toBe('generated');
        expect(generated.risk.noise).toBe(true);

        const trailingMarker = classifyFile({
            path: 'src/api/client.ts',
            content: `${'x'.repeat(GENERATED_MARKER_BYTES * 2)}\n// @generated`,
            rules: RULES
        });

        expect(trailingMarker.classification).toBe('source');

        const sqlException = classifyFile({
            path: 'db/migrations/001_init.sql',
            content: '-- Code generated by migration tool',
            rules: RULES
        });

        expect(sqlException.classification).toBe('source');

        const migrationException = classifyFile({
            path: 'db/migrations/001_init.ts',
            content: '// Generated by tool',
            rules: RULES
        });

        expect(migrationException.classification).toBe('source');

        const unmarked = classifyFile({ path: 'src/api/client.ts', content: 'export {};', rules: RULES });
        expect(unmarked.classification).toBe('source');
        expect(unmarked.risk.noise).toBe(false);

        const empty = classifyFile({ path: 'src/api/client.ts', content: '', rules: RULES });
        expect(empty.classification).toBe('source');
        expect(empty.risk.noise).toBe(false);
    });

    test('a rename cannot launder a noise class into source', () => {
        const renamed = classifyFile({ path: 'src/data.json', previousPath: 'bun.lock', rules: RULES });
        expect(renamed.classification).toBe('lockfile');
        expect(classifyFile({ path: 'vendor/lib.ts', previousPath: 'src/lib.ts', rules: RULES }).classification).toBe(
            'vendor'
        );
    });
});

describe('classification-driven risk volume', () => {
    test('noise files stay visible but do not inflate source-code metrics', () => {
        const risk = assessRisk({
            changedFiles: [
                changedFile('bun.lock', 400),
                changedFile('assets/logo.png', 300),
                changedFile('src/app.ts', 10)
            ],
            recognizedFilesCount: 1000,
            physicalLines: 100_000
        });

        expect(risk.noiseFilesCount).toBe(2);
        expect(risk.changedFilesCount).toBe(1);
        expect(risk.changedLines).toBe(10);
    });

    test('a pre-pass generated classification excludes a source path from volume', () => {
        const classifications = new Map([
            ['src/api/client.ts', classifyFile({ path: 'src/api/client.ts', content: '@generated', rules: RULES })]
        ]);

        const risk = assessRisk({
            changedFiles: [changedFile('src/api/client.ts', 500)],
            recognizedFilesCount: 1000,
            physicalLines: 100_000,
            fileClassifications: classifications
        });

        expect(risk.noiseFilesCount).toBe(1);
        expect(risk.changedFilesCount).toBe(0);
        expect(risk.tier).toBe('lite');
    });

    test('a changed lockfile still escalates dependencies without adding volume', () => {
        const risk = assessRisk({
            changedFiles: [changedFile('bun.lock', 500)],
            recognizedFilesCount: 1000,
            physicalLines: 100_000
        });

        expect(risk.changedFilesCount).toBe(0);
        expect(risk.noiseFilesCount).toBe(1);
        expect(risk.signals.map((signal) => signal.id)).toContain('dependencies');
        expect(risk.tier).toBe('standard');
    });

    test('configured classification replaces the default path-class patterns', () => {
        const configured = { ...RULES, criticalPathPatterns: ['custom/critical/**'], securityPathPatterns: [] };
        const rules = riskRulesForClassification(configured);
        expect(rules.escalations.find((rule) => rule.id === 'critical-paths')?.patterns).toEqual([
            'custom/critical/**'
        ]);

        const risk = assessRisk({
            changedFiles: [changedFile('auth/login.ts', 4)],
            recognizedFilesCount: 1000,
            physicalLines: 100_000,
            classification: configured,
            rules
        });

        expect(risk.signals.map((signal) => signal.id)).not.toContain('critical-paths');
        expect(risk.signals.map((signal) => signal.id)).not.toContain('security');
    });
});
